#!/bin/bash
set -e

#UNIX

#http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html

#Packages installed (other ones probably needed): 
#libavcodec-dev, libavformat-dev, libswscale-dev, etc: all ones that are not optional

#Download .zip from their website
sudo wget http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip

#Unzip
unzip opencv-2.4.9.zip

#mkdir tmp and enter
mkdir tmp
pushd tmp
	#cmake <path of unzipped library>
	cmake ../opencv-2.4.9
	#make
	make
	#sudo make install
	sudo make install
popd
