#!/bin/bash
set -e

#hdf5 required
# If using homebrew:
# brew tap homebrew/science
# brew install hdf5


######
#1 OpenCV
######

#UNIX

#http://docs.opencv.org/doc/tutorials/introduction/linux_install/linux_install.html

#Packages installed (other ones probably needed): 
#libavcodec-dev, libavformat-dev, libswscale-dev, etc: all ones that are not optional

#Download .zip from their website
sudo wget http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip

# #Unzip
unzip opencv-2.4.9.zip

# #mkdir tmp and enter
mkdir tmp
pushd tmp
	#cmake <path of unzipped library>
	cmake ../opencv-2.4.9.zip
	#make
	make
	#sudo make install
	sudo make install
popd

#Remove installation files
rm -rf opencv-2.4.9.zip
rm -rf tmp
rm -rf opencv-2.4.9

#####
# 2 Armadillo
#####

wget http://sourceforge.net/projects/arma/files/armadillo-4.400.1.tar.gz

gunzip armadillo-4.400.1.tar.gz
tar -xvf armadillo-4.400.1.tar

pushd armadillo-4.400.1
	cmake ../armadillo-4.400.1
	make
	sudo make install
popd

#Remove installation files
rm -rf armadillo-4.400.1.tar
rm -rf armadillo-4.400.1

####
#3 Compile CapSolv
####

pushd src
	cmake .
	make
popd


